### PR TITLE
Add stub build command for etest-build.

### PR DESCRIPTION
**Pull request by alunduil**
We don't want to use a shell script to manage such a core piece of the
packaging and want something mildly testable.  This stubs a python click
command to build Docker images for etest that we can re-use in other
places if desired and build a multitude of images (this could easily be
reused in Google cloud builds for example.

Note this is only a stub and the logic still needs to either be ported
from the shell script or added.  Let me know if you'd like me to just
add that functionality in this pull request (seems like a fine idea to
me), but I will need review that I'm converting the logic correctly as
BASH is finicky and quite easy to misinterpret.

### CODE REVIEW

**Comment by alunduil** [comment]
This should close #89 once landed.

**Review by LinoBigatti — APPROVED** [review]
All seems good to me. I will see how to integrate it and merge into cross-arch

**Comment by alunduil** [comment]
Hmm, how did this merge with the checks failing?

**Comment by LinoBigatti** [comment]
I dont think checks are inforced. I merged it manually and planned to fix test coverage for it in #89

**Comment by alunduil** [comment]
Ah, we should see why checks aren't enforced.  They are on my other projects.  I'll play with it and see what I can scrounge up.

**Pull request merged**
